title: 'L'Appart'
description: "Présentation de L'Appart"
baseurl: "/jekyll-theme-console"
url: "https://appart404.github.io"

header_pages:
  - index.md
  - rejoindre.md
  - about.md

style: dark

footer: 'Suivez-nous sur <a href="https://twitter.com/AppartOff">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
