title: 'appart404.github.io'
description: "site description for seo"
baseurl: "/wall"
url: "https://appart404.github.io"

header_pages:
  - index.md
  - rejoindre.md
  - infos.md

style: dark

footer: 'suivez-nous sur <a href="https://twitter.com/AppartOff">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
